### Получить всех сотрудников
GET http://localhost:8080/employees
// localhost:8080 - это текущий локальный компьютер, например мой
// Нажимаем Плей и внизу видим результат запроса.
// Здесь HTTP/1.1 200 код 200 означает что запрос выполнен успешно
// Далее заголовки. Самый интересный Content-Type: который говорит что находится в ответе У нас это application/json

### Получить сумму зарплат по сотрудникам
GET http://localhost:8080/employees/salary/sum

### Напечатать Привет,мир!
GET http://localhost:8080/helloWorld

### Получение сотрудника с минимальной зарплатой
GET http://localhost:8080/employees/salary/min

### Получение сотрудника с максимальной зарплатой
GET http://localhost:8080/employees/salary/max

### Получение всех сотрудников, зарплата которых больше средней
GET http://localhost:8080/employees/salary/high-salary